BOTTLE_CONTENT_MANAGER_API_PORT = 8081
BOTTLE_DEORATOR_PORTFOLIOS_API_PORT = 8082
BOTTLE_DEORATOR_TAGS_API_PORT = 8083
BOTTLE_DEORATOR_VOTES_API_PORT = 8084

CONTENT_SOLR_URL = 'http://localhost:8984/solr'
DECORATION_SOLR_URL = 'http://localhost:8984/solr'
DECORATION_SOLR_FIELD_0 = 'portfolios'
DECORATION_SOLR_FIELD_1 = 'tags'


